inputs:
  access_key_id:
    required: true
  secret_access_key:
    required: true
  ref_name:
    required: true
  default_region:
    required: true

runs:
  using: docker
  image: ./DockerfileSW
  args:
    - ${{ inputs.default_region }}
    - ${{ inputs.access_key_id }}
    - ${{ inputs.secret_access_key }}
    - ${{ inputs.ref_name }}