inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    name: Checkout
  - uses: actions/setup-python@v4
    with:
      python-version: '3.10'
  - name: Install Python dependencies
    run: |
      python -m pip install pip -U
      python -m pip install -r requirements/deploy.txt
    shell: bash
  - name: Deploy
    uses: yeslayla/zappa-deploy-action@v0.1.1
    with:
      directory: .
      environment: ${{ github.ref_name }}
    env:
      AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}